// Datos de recetas, productos e información de los tés — NICE Imperial Matcha & Rooibos
// Fuente: recetario oficial NICE (references/recetario.pdf)

const RECETAS = [
  // ── MATCHA · BEBIDAS ──
  {
    id: 'matcha-latte', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Latte',
    porciones: '1', imagen: 'assets/images/matcha-latte.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Imperial Matcha Green Tea Ceremonial',
      '1/4 taza de agua caliente',
      '1 taza de leche caliente (cualquiera de tu preferencia)',
      'Endulzante al gusto (azúcar, miel o jarabe)',
    ],
    instrucciones: [
      'En una taza, mezcla el matcha con el agua caliente hasta que quede bien disuelto.',
      'Agrega la leche caliente y mezcla.',
      'Endulza al gusto.',
    ],
  },
  {
    id: 'limonada-matcha', te: 'matcha', tipo: 'bebida', nombre: 'Limonada de Matcha',
    porciones: '1', imagen: 'assets/images/limonada-matcha.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Imperial Matcha Green Tea Limón',
      '1 taza de agua',
      '1/4 de taza de jugo de limón fresco',
      'Hielo al gusto',
      'Rodajas de limón al gusto',
    ],
    instrucciones: [
      'En un vaso, mezcla el matcha con el agua hasta que quede bien disuelto.',
      'Agrega el jugo de limón y mezcla.',
      'Sirve sobre hielo y decora con rodajas de limón.',
    ],
  },
  {
    id: 'smoothie-matcha-vainilla', te: 'matcha', tipo: 'bebida', nombre: 'Smoothie Matcha & Vainilla',
    porciones: '1', imagen: 'assets/images/smoothie-matcha-vainilla.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Imperial Matcha Green Tea',
      '1 plátano maduro',
      '1 taza de espinacas',
      '1/2 taza de yogurt natural',
      '1/2 taza de leche (cualquiera de tu preferencia)',
      'Extracto de vainilla al gusto',
      'Miel al gusto',
    ],
    instrucciones: [
      'Coloca todos los ingredientes en una licuadora y mezcla hasta que quede suave.',
      'Agrega extracto de vainilla al gusto y endulza con miel.',
    ],
  },
  {
    id: 'matcha-pumpkin-spiced', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Pumpkin Spiced',
    porciones: '1', imagen: 'assets/images/matcha-pumpkin-spiced.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Imperial Matcha Green Tea',
      '1 taza de leche (cualquiera de tu preferencia)',
      '1/2 taza de puré de calabaza',
      '1/4 de cucharadita de canela en polvo',
      '1/4 de cucharadita de nuez moscada',
      'Endulzante al gusto (azúcar, miel o jarabe)',
      '1/4 taza de agua caliente',
    ],
    instrucciones: [
      'Mezcla el matcha con un poco de agua caliente hasta que quede bien disuelto.',
      'En un sartén, calienta la leche y el puré de calabaza.',
      'Agrega la canela en polvo, la nuez moscada y la mezcla de matcha.',
      'Endulza al gusto y sirve caliente.',
    ],
  },
  {
    id: 'matcha-tricolor', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Tricolor',
    porciones: '1', imagen: 'assets/images/matcha-tricolor.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Imperial Matcha Green Tea',
      '1 3/4 tazas de leche (cualquiera de tu preferencia)',
      '5 fresas',
      'Endulzante al gusto (azúcar, miel o jarabe de fresa)',
    ],
    instrucciones: [
      'Prepara la mezcla de matcha en 1 taza de leche y deja reposar.',
      'Licúa las fresas.',
      'Vierte en un vaso las fresas licuadas, la leche sola y finalmente la mezcla de matcha.',
      'Sirve con una cuchara larga para mezclar los sabores antes de beber.',
    ],
  },
  // ── MATCHA · PLATILLOS ──
  {
    id: 'hotcakes-matcha', te: 'matcha', tipo: 'platillo', nombre: 'Hotcakes de Matcha',
    porciones: '5 - 7 hotcakes', imagen: 'assets/images/hotcakes-matcha.jpeg',
    ingredientes: [
      '1 cucharada de NICE Imperial Matcha Green Tea',
      '1 taza de harina de trigo',
      '1 cucharada de azúcar',
      '1 1/2 cucharaditas de polvo para hornear',
      '1/4 de cucharadita de sal',
      '1 huevo',
      '1 taza de leche (cualquiera de tu preferencia)',
      '2 cucharadas de mantequilla derretida',
      'Aceite para cocinar',
      'Endulzante al gusto (jarabe o miel)',
    ],
    instrucciones: [
      'En un tazón grande, mezcla el matcha con la harina, el azúcar, el polvo de hornear y la sal.',
      'En otro tazón, bate el huevo y luego agrega la leche y la mantequilla derretida.',
      'Vierte la mezcla húmeda en la mezcla seca y revuelve hasta que estén perfectamente integradas.',
      'Agrega un poco de aceite a un sartén y calienta a fuego medio.',
      'Vierte 1/4 de taza de masa por hotcake en el sartén caliente.',
      'Cocina hasta que aparezcan burbujas en la superficie y dales la vuelta para cocinar del otro lado.',
      'Sirve caliente con miel o jarabe.',
    ],
  },
  {
    id: 'matcha-hummus', te: 'matcha', tipo: 'platillo', nombre: 'Matcha Hummus',
    porciones: '4 - 6 (2 cucharadas por porción)', imagen: 'assets/images/matcha-hummus.jpeg',
    ingredientes: [
      '2 cucharaditas de NICE Imperial Matcha Green Tea',
      '1 lata de garbanzos, escurridos y enjuagados',
      '2 cucharadas de tahini (pasta de sésamo)',
      '1 cucharada de aceite de oliva',
      '2 dientes de ajo pelados',
      'Jugo de 1 limón',
      'Sal y pimienta al gusto',
      'Agua (opcional, para ajustar la consistencia)',
      'Pan pita, galletas saladas o verduras al gusto',
    ],
    instrucciones: [
      'Coloca todos los ingredientes en un procesador de alimentos.',
      'Procesa hasta que la mezcla esté suave y bien integrada. Si es necesario, agrega un poco de agua.',
      'Prueba y ajusta la sal y la pimienta según tu preferencia.',
      'Sirve con pan pita, galletas saladas o verduras.',
    ],
  },
  {
    id: 'helado-te-matcha', te: 'matcha', tipo: 'platillo', nombre: 'Helado de Té Matcha',
    porciones: '6', imagen: 'assets/images/helado-te-matcha.jpeg',
    ingredientes: [
      '2 cucharadas de NICE Imperial Matcha Green Tea',
      '2 tazas de crema para batir',
      '1 taza de leche (cualquiera de tu preferencia)',
      '3/4 de taza de azúcar',
      '1 cucharadita de extracto de vainilla',
    ],
    instrucciones: [
      'En un tazón grande, mezcla el matcha en polvo con una pequeña cantidad de leche para disolverlo bien.',
      'En una cacerola, calienta el resto de la leche y el azúcar, revuelve hasta que el azúcar se disuelva.',
      'Vierte la mezcla caliente sobre la de matcha y revuelve hasta que estén bien integradas.',
      'Agrega la crema para batir y el extracto de vainilla y mezcla bien.',
      'Congela la mezcla durante al menos 45 minutos o hasta que esté completamente fría.',
      'Saca el tazón, mezcla durante 2 minutos y repite el procedimiento hasta la consistencia deseada.',
      'Sirve y disfruta.',
    ],
  },
  {
    id: 'galletas-matcha', te: 'matcha', tipo: 'platillo', nombre: 'Galletas de Matcha',
    porciones: '5 - 6 galletas', imagen: 'assets/images/galletas-matcha.jpeg',
    ingredientes: [
      '1 1/2 tazas de harina de trigo',
      '1 cucharadita de NICE Imperial Matcha Green Tea',
      '1/2 cucharadita de polvo para hornear',
      '1/4 de cucharadita de sal',
      '1/2 taza de mantequilla a temperatura ambiente',
      '3/4 de taza de azúcar',
      '1 huevo',
      '1 cucharadita de extracto de vainilla',
      'Azúcar glas al gusto',
    ],
    instrucciones: [
      'Mezcla la harina con el matcha, el polvo para hornear y la sal.',
      'En otro tazón, bate la mantequilla y el azúcar hasta que la mezcla esté suave y cremosa.',
      'Agrega el huevo y el extracto de vainilla y sigue batiendo hasta integrar.',
      'Une ambas mezclas hasta formar una masa.',
      'Cubre la masa y refrigera durante al menos 1 hora.',
      'Precalienta el horno a 180°C y forra una bandeja con papel para hornear.',
      'Divide la masa en pequeñas bolas y colócalas en la bandeja, dejando espacio entre cada una.',
      'Hornea 10-12 minutos o hasta que doren en los bordes.',
      'Deja enfriar unos minutos antes de pasarlas a una rejilla.',
      'Espolvorea con azúcar glas antes de servir, si gustas.',
    ],
  },
  {
    id: 'gelatina-matcha', te: 'matcha', tipo: 'platillo', nombre: 'Gelatina de Matcha',
    porciones: '2', imagen: 'assets/images/gelatina-matcha.jpeg',
    ingredientes: [
      '2 cucharaditas de NICE Imperial Matcha Green Tea Ceremonial',
      '1 taza de agua caliente',
      '3 cucharaditas de grenetina',
      '1/2 taza de azúcar',
      '1 taza de agua fría',
    ],
    instrucciones: [
      'Disuelve el matcha con agua caliente.',
      'En un tazón grande, revuelve la grenetina en polvo con la taza de agua fría.',
      'Agrega la mezcla de matcha caliente y el azúcar a la grenetina.',
      'Revuelve hasta que la grenetina y el azúcar se disuelvan por completo.',
      'Vierte en moldes individuales o un molde grande.',
      'Refrigera al menos 4 horas o hasta que cuaje firme.',
      'Desmolda y sirve.',
    ],
  },
  // ── ROOIBOS · BEBIDAS ──
  {
    id: 'rooibos-latte', te: 'rooibos', tipo: 'bebida', nombre: 'Rooibos Latte',
    porciones: '1', imagen: 'assets/images/rooibos-latte.jpeg',
    ingredientes: [
      '1 taza de leche caliente (cualquiera de tu preferencia)',
      '1 cucharadita de NICE Rooibos Red Tea',
      'Endulzante al gusto (azúcar, miel o jarabe)',
      'Extracto de vainilla al gusto',
    ],
    instrucciones: [
      'Mezcla la leche caliente con el rooibos y deja reposar 5-7 minutos.',
      'Endulza al gusto y, si lo deseas, agrega extracto de vainilla.',
      'Sirve caliente.',
    ],
  },
  {
    id: 'limonada-rooibos', te: 'rooibos', tipo: 'bebida', nombre: 'Limonada de Rooibos',
    porciones: '1', imagen: 'assets/images/limonada-rooibos.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Rooibos Red Tea',
      '1 taza de agua caliente',
      '1/4 de taza de jugo de limón',
      'Hielo al gusto',
      'Rodajas de limón al gusto',
      'Endulzante al gusto (azúcar, miel o jarabe)',
    ],
    instrucciones: [
      'En un vaso, agrega el rooibos y vierte el agua caliente, mezcla bien. Deja reposar 5-7 minutos y vuelve a mezclar.',
      'Agrega el jugo de limón y el endulzante. Mezcla hasta disolver.',
      'Sirve sobre hielo y decora con rodajas de limón.',
    ],
  },
  {
    id: 'rooibos-sangria', te: 'rooibos', tipo: 'bebida', nombre: 'Rooibos Rojo Sangría',
    porciones: '1', imagen: 'assets/images/rooibos-sangria.jpeg',
    ingredientes: [
      '4 cucharadas de NICE Rooibos Red Tea',
      '2 tazas de agua caliente',
      '4 tazas de jugo de uva',
      '1/2 taza de refresco de limón o toronja',
      '1/4 de taza de jugo de naranja',
      '1/4 de taza de jugo de limón',
      'Frutas frescas (naranjas, manzanas, fresas, uvas)',
      'Rodajas de naranja y limón para decorar',
      'Hielo al gusto',
    ],
    instrucciones: [
      'Mezcla el rooibos con el agua caliente.',
      'Deja reposar 10-15 minutos y mezcla bien.',
      'En una jarra grande, revuelve la mezcla de rooibos con el jugo de uva, el refresco, el jugo de naranja y el jugo de limón.',
      'Refrigera al menos 2 horas antes de servir.',
      'Sirve con frutas frescas, rodajas de limón, naranja y hielo al gusto.',
    ],
  },
  {
    id: 'rooibos-calientito-miel', te: 'rooibos', tipo: 'bebida', nombre: 'Rooibos Calientito con Miel',
    porciones: '1', imagen: 'assets/images/rooibos-calientito-miel.jpeg',
    ingredientes: [
      '1 taza de agua o leche caliente (cualquiera de tu preferencia)',
      '1 cucharadita de NICE Rooibos Red Tea',
      'Miel al gusto',
    ],
    instrucciones: [
      'Agrega el rooibos al agua o leche caliente y deja reposar 5-7 minutos.',
      'Endulza con miel al gusto y sirve caliente.',
    ],
  },
  // ── ROOIBOS · PLATILLOS ──
  {
    id: 'helado-rooibos', te: 'rooibos', tipo: 'platillo', nombre: 'Helado de Rooibos',
    porciones: '2', imagen: 'assets/images/helado-rooibos.jpeg',
    ingredientes: [
      '3 cucharaditas de NICE Rooibos Red Tea',
      '1 taza de leche caliente (cualquiera de tu preferencia)',
      '2 tazas de crema para batir',
      '3/4 de taza de azúcar',
    ],
    instrucciones: [
      'Disuelve el rooibos en leche caliente y deja reposar 10-15 minutos.',
      'En un tazón grande, revuelve la mezcla con la crema para batir y el azúcar hasta disolver.',
      'Refrigera al menos 4 horas o hasta que esté completamente fría.',
      'Vierte en un tazón y congela 45 minutos.',
      'Mezcla 2 minutos y repite el procedimiento hasta la consistencia deseada.',
      'Sirve y disfruta.',
    ],
  },
  {
    id: 'natilla-rooibos', te: 'rooibos', tipo: 'platillo', nombre: 'Natilla de Rooibos',
    porciones: '3', imagen: 'assets/images/natilla-rooibos.jpeg',
    ingredientes: [
      '2 tazas de leche caliente (cualquiera de tu preferencia)',
      '2 cucharaditas de NICE Rooibos Red Tea',
      '1/4 de taza de azúcar',
      '2 cucharadas de maicena',
      '2 yemas de huevo',
      '1 cucharadita de extracto de vainilla',
      'Fresas al gusto',
    ],
    instrucciones: [
      'Disuelve el rooibos en la leche caliente.',
      'En un sartén, mezcla el azúcar y la maicena.',
      'Agrega la leche de rooibos y las yemas de huevo. Cocina a fuego medio-bajo, revolviendo hasta que espese.',
      'Retira del fuego y agrega el extracto de vainilla.',
      'Deja enfriar y sirve con fresas al gusto.',
    ],
  },
  {
    id: 'panque-naranja-rooibos', te: 'rooibos', tipo: 'platillo', nombre: 'Panqué de Naranja & Rooibos',
    porciones: '7', imagen: 'assets/images/panque-naranja-rooibos.jpeg',
    ingredientes: [
      '1 1/2 tazas de harina',
      '2 cucharaditas de polvo de hornear',
      '1/2 cucharadita de sal',
      '1 taza de agua caliente',
      '2 cucharaditas de NICE Rooibos Red Tea',
      '1/2 taza de leche (cualquiera de tu preferencia)',
      '1/2 taza de jugo de naranja fresco',
      '1/2 taza de azúcar',
      '1/4 de taza de mantequilla derretida',
      '2 huevos',
      'Rodajas de naranja, pasas o arándanos al gusto',
    ],
    instrucciones: [
      'Precalienta el horno a 180°C y engrasa un molde para panqué.',
      'Mezcla la harina, el polvo para hornear y la sal.',
      'Disuelve el rooibos en el agua caliente y deja reposar 5-7 minutos.',
      'Separa dos mezclas: una con el rooibos, la leche, el jugo de naranja, el azúcar, la mantequilla y los huevos; otra con los secos.',
      'Une ambas mezclas hasta obtener una consistencia suave. Agrega pasas o arándanos si gustas.',
      'Vierte la masa en el molde y hornea 45-50 minutos (palillo debe salir limpio).',
      'Deja enfriar en el molde y luego desmolda.',
      'Decora con rodajas de naranja antes de servir.',
    ],
  },
  {
    id: 'pastel-miel-rooibos', te: 'rooibos', tipo: 'platillo', nombre: 'Pastel de Miel & Rooibos',
    porciones: '5', imagen: 'assets/images/pastel-miel-rooibos.jpeg',
    ingredientes: [
      '1 1/2 tazas de harina',
      '2 cucharaditas de polvo de hornear',
      '1/2 cucharadita de sal',
      '2 cucharaditas de NICE Rooibos Red Tea',
      '1 taza de agua caliente',
      '1/2 taza de leche',
      '1/2 taza de miel',
      '1/4 de taza de mantequilla derretida',
      '2 huevos',
      'Azúcar glas al gusto',
    ],
    instrucciones: [
      'Precalienta el horno a 180°C y engrasa un molde para pastel.',
      'Mezcla la harina, el polvo de hornear y la sal.',
      'Mezcla el rooibos con el agua caliente y deja reposar 5-7 minutos.',
      'Agrega el rooibos, la leche, la miel, la mantequilla y los huevos a los secos.',
      'Mezcla hasta que la masa esté suave.',
      'Vierte en el molde y hornea 30-35 minutos (palillo debe salir limpio).',
      'Deja enfriar en el molde y desmolda.',
      'Espolvorea con azúcar glas antes de servir.',
    ],
  },
  {
    id: 'paletas-rooibos-frutos-rojos', te: 'rooibos', tipo: 'platillo', nombre: 'Paletas de Rooibos con Frutos Rojos',
    porciones: '5 - 7 paletas', imagen: 'assets/images/paletas-rooibos-frutos-rojos.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Rooibos Red Tea',
      '1 taza de agua caliente',
      '1 taza de frutos rojos (fresas, frambuesas, moras, etc.)',
      '1/4 de taza de yogurt natural',
      'Endulzante al gusto (azúcar, miel o jarabe)',
    ],
    instrucciones: [
      'Mezcla el rooibos con el agua caliente y el endulzante de tu preferencia.',
      'Deja enfriar la mezcla.',
      'Licúa el rooibos endulzado con los frutos rojos y el yogurt hasta obtener una mezcla suave.',
      'Vierte en moldes para paletas y congela al menos 4 horas.',
    ],
  },
  {
    id: 'sopa-tomate-fria', te: 'rooibos', tipo: 'platillo', nombre: 'Sopa de Tomate Fría',
    porciones: '4', imagen: 'assets/images/sopa-tomate-fria.jpeg',
    ingredientes: [
      '6 tomates maduros',
      '1 cucharada de NICE Rooibos Red Tea',
      '1/2 taza de agua caliente',
      '1 diente de ajo',
      '1/4 de taza de aceite de oliva',
      '2 cucharadas de vinagre balsámico',
      'Sal y pimienta al gusto',
      'Hojas de albahaca fresca para decorar',
    ],
    instrucciones: [
      'Mezcla el rooibos con el agua caliente.',
      'Licúa los tomates, el ajo, el aceite de oliva, el vinagre balsámico y la infusión de rooibos hasta obtener una mezcla suave.',
      'Sazona con sal y pimienta al gusto.',
      'Refrigera al menos 2 horas antes de servir.',
      'Sirve fría, decorada con hojas de albahaca fresca.',
    ],
  },
]

const PRODUCTOS = [
  {
    id: 'matcha-ceremonial', nombre: 'Matcha Ceremonial 100% Pure', te: 'matcha',
    imagen: 'assets/images/matcha-section.jpeg',
    descripcion: 'Té verde matcha molido, 100% puro, calidad ceremonial. Ideal para prepararlo tradicional o en latte.',
    presentacion: '2.46 oz (70 g)',
    precio: null,
  },
  {
    id: 'matcha-premium-lime', nombre: 'Matcha Premium Quality — Sabor Lime', te: 'matcha',
    imagen: 'assets/images/limonada-matcha.jpeg',
    descripcion: 'Té verde matcha premium con un toque de limón, en sobres individuales listos para llevar.',
    presentacion: '28 sobres',
    precio: null,
  },
  {
    id: 'rooibos-red-tea', nombre: 'NICE Rooibos Red Tea', te: 'rooibos',
    imagen: 'assets/images/rooibos-section.jpeg',
    descripcion: 'Té rojo en polvo, sin cafeína, sabor suave. Ideal para toda la familia, caliente o frío.',
    presentacion: '3.52 oz (100 g)',
    precio: null,
  },
]

const INFO_TES = {
  matcha: {
    titulo: 'Matcha',
    beneficios: [
      { t: 'Té verde concentrado', d: 'Una taza de matcha puede tener el valor nutricional de 10 tazas de té verde.' },
      { t: 'Poder antioxidante', d: 'El té matcha cuenta con más antioxidantes que cualquier otra variedad de té.' },
      { t: 'Ayuda a mejorar la apariencia de la piel', d: 'El matcha contiene nutrientes sorprendentes para tu piel, como la clorofila y vitaminas.' },
      { t: 'Energía revitalizante', d: 'La teína que contiene el matcha se procesa de forma más lenta, haciendo que la energía dure mucho más.' },
    ],
  },
  rooibos: {
    titulo: 'Rooibos',
    beneficios: [
      { t: 'Sin cafeína', d: 'El té rooibos es libre de cafeína, excelente opción para quienes tienen problemas para dormir.' },
      { t: 'Relajante', d: 'Tiene propiedades calmantes, puede ayudar a reducir el estrés y promover un descanso profundo.' },
      { t: 'Buena opción para niños', d: 'Por su sabor suave, el rooibos suele gustarle a los niños — una alternativa más saludable a las bebidas azucaradas.' },
    ],
  },
}
