// Datos de recetas, productos e información de los tés — NICE Imperial Matcha & Rooibos
// Fuente: recetario oficial NICE (references/recetario.pdf)

const RECETAS = [
  // ── MATCHA · BEBIDAS ──
  {
    id: 'matcha-latte', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Latte',
    porciones: '1', imagen: 'assets/images/matcha-latte.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Imperial Matcha Green Tea Ceremonial',
      '1/4 taza de agua caliente',
      '1 taza de leche caliente (cualquiera de tu preferencia)',
      'Endulzante al gusto (azúcar, miel o jarabe)',
    ],
    instrucciones: [
      'En una taza, mezcla el matcha con el agua caliente hasta que quede bien disuelto.',
      'Agrega la leche caliente y mezcla.',
      'Endulza al gusto.',
    ],
  },
  {
    id: 'limonada-matcha', te: 'matcha', tipo: 'bebida', nombre: 'Limonada de Matcha',
    porciones: '1', imagen: 'assets/images/limonada-matcha.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Imperial Matcha Green Tea Limón',
      '1 taza de agua',
      '1/4 de taza de jugo de limón fresco',
      'Hielo al gusto',
      'Rodajas de limón al gusto',
    ],
    instrucciones: [
      'En un vaso, mezcla el matcha con el agua hasta que quede bien disuelto.',
      'Agrega el jugo de limón y mezcla.',
      'Sirve sobre hielo y decora con rodajas de limón.',
    ],
  },
  {
    id: 'smoothie-matcha-vainilla', te: 'matcha', tipo: 'bebida', nombre: 'Smoothie Matcha & Vainilla',
    porciones: '1', imagen: 'assets/images/smoothie-matcha-vainilla.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Imperial Matcha Green Tea',
      '1 plátano maduro',
      '1 taza de espinacas',
      '1/2 taza de yogurt natural',
      '1/2 taza de leche (cualquiera de tu preferencia)',
      'Extracto de vainilla al gusto',
      'Miel al gusto',
    ],
    instrucciones: [
      'Coloca todos los ingredientes en una licuadora y mezcla hasta que quede suave.',
      'Agrega extracto de vainilla al gusto y endulza con miel.',
    ],
  },
  {
    id: 'matcha-pumpkin-spiced', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Pumpkin Spiced',
    porciones: '1', imagen: 'assets/images/matcha-pumpkin-spiced.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Imperial Matcha Green Tea',
      '1 taza de leche (cualquiera de tu preferencia)',
      '1/2 taza de puré de calabaza',
      '1/4 de cucharadita de canela en polvo',
      '1/4 de cucharadita de nuez moscada',
      'Endulzante al gusto (azúcar, miel o jarabe)',
      '1/4 taza de agua caliente',
    ],
    instrucciones: [
      'Mezcla el matcha con un poco de agua caliente hasta que quede bien disuelto.',
      'En un sartén, calienta la leche y el puré de calabaza.',
      'Agrega la canela en polvo, la nuez moscada y la mezcla de matcha.',
      'Endulza al gusto y sirve caliente.',
    ],
  },
  {
    id: 'matcha-tricolor', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Tricolor',
    porciones: '1', imagen: 'assets/images/matcha-tricolor.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Imperial Matcha Green Tea',
      '1 3/4 tazas de leche (cualquiera de tu preferencia)',
      '5 fresas',
      'Endulzante al gusto (azúcar, miel o jarabe de fresa)',
    ],
    instrucciones: [
      'Prepara la mezcla de matcha en 1 taza de leche y deja reposar.',
      'Licúa las fresas.',
      'Vierte en un vaso las fresas licuadas, la leche sola y finalmente la mezcla de matcha.',
      'Sirve con una cuchara larga para mezclar los sabores antes de beber.',
    ],
  },
  // ── MATCHA · PLATILLOS ──
  {
    id: 'hotcakes-matcha', te: 'matcha', tipo: 'platillo', nombre: 'Hotcakes de Matcha',
    porciones: '5 - 7 hotcakes', imagen: 'assets/images/hotcakes-matcha.jpeg',
    ingredientes: [
      '1 cucharada de NICE Imperial Matcha Green Tea',
      '1 taza de harina de trigo',
      '1 cucharada de azúcar',
      '1 1/2 cucharaditas de polvo para hornear',
      '1/4 de cucharadita de sal',
      '1 huevo',
      '1 taza de leche (cualquiera de tu preferencia)',
      '2 cucharadas de mantequilla derretida',
      'Aceite para cocinar',
      'Endulzante al gusto (jarabe o miel)',
    ],
    instrucciones: [
      'En un tazón grande, mezcla el matcha con la harina, el azúcar, el polvo de hornear y la sal.',
      'En otro tazón, bate el huevo y luego agrega la leche y la mantequilla derretida.',
      'Vierte la mezcla húmeda en la mezcla seca y revuelve hasta que estén perfectamente integradas.',
      'Agrega un poco de aceite a un sartén y calienta a fuego medio.',
      'Vierte 1/4 de taza de masa por hotcake en el sartén caliente.',
      'Cocina hasta que aparezcan burbujas en la superficie y dales la vuelta para cocinar del otro lado.',
      'Sirve caliente con miel o jarabe.',
    ],
  },
  {
    id: 'matcha-hummus', te: 'matcha', tipo: 'platillo', nombre: 'Matcha Hummus',
    porciones: '4 - 6 (2 cucharadas por porción)', imagen: 'assets/images/matcha-hummus.jpeg',
    ingredientes: [
      '2 cucharaditas de NICE Imperial Matcha Green Tea',
      '1 lata de garbanzos, escurridos y enjuagados',
      '2 cucharadas de tahini (pasta de sésamo)',
      '1 cucharada de aceite de oliva',
      '2 dientes de ajo pelados',
      'Jugo de 1 limón',
      'Sal y pimienta al gusto',
      'Agua (opcional, para ajustar la consistencia)',
      'Pan pita, galletas saladas o verduras al gusto',
    ],
    instrucciones: [
      'Coloca todos los ingredientes en un procesador de alimentos.',
      'Procesa hasta que la mezcla esté suave y bien integrada. Si es necesario, agrega un poco de agua.',
      'Prueba y ajusta la sal y la pimienta según tu preferencia.',
      'Sirve con pan pita, galletas saladas o verduras.',
    ],
  },
  {
    id: 'helado-te-matcha', te: 'matcha', tipo: 'platillo', nombre: 'Helado de Té Matcha',
    porciones: '6', imagen: 'assets/images/helado-te-matcha.jpeg',
    ingredientes: [
      '2 cucharadas de NICE Imperial Matcha Green Tea',
      '2 tazas de crema para batir',
      '1 taza de leche (cualquiera de tu preferencia)',
      '3/4 de taza de azúcar',
      '1 cucharadita de extracto de vainilla',
    ],
    instrucciones: [
      'En un tazón grande, mezcla el matcha en polvo con una pequeña cantidad de leche para disolverlo bien.',
      'En una cacerola, calienta el resto de la leche y el azúcar, revuelve hasta que el azúcar se disuelva.',
      'Vierte la mezcla caliente sobre la de matcha y revuelve hasta que estén bien integradas.',
      'Agrega la crema para batir y el extracto de vainilla y mezcla bien.',
      'Congela la mezcla durante al menos 45 minutos o hasta que esté completamente fría.',
      'Saca el tazón, mezcla durante 2 minutos y repite el procedimiento hasta la consistencia deseada.',
      'Sirve y disfruta.',
    ],
  },
  {
    id: 'galletas-matcha', te: 'matcha', tipo: 'platillo', nombre: 'Galletas de Matcha',
    porciones: '5 - 6 galletas', imagen: 'assets/images/galletas-matcha.jpeg',
    ingredientes: [
      '1 1/2 tazas de harina de trigo',
      '1 cucharadita de NICE Imperial Matcha Green Tea',
      '1/2 cucharadita de polvo para hornear',
      '1/4 de cucharadita de sal',
      '1/2 taza de mantequilla a temperatura ambiente',
      '3/4 de taza de azúcar',
      '1 huevo',
      '1 cucharadita de extracto de vainilla',
      'Azúcar glas al gusto',
    ],
    instrucciones: [
      'Mezcla la harina con el matcha, el polvo para hornear y la sal.',
      'En otro tazón, bate la mantequilla y el azúcar hasta que la mezcla esté suave y cremosa.',
      'Agrega el huevo y el extracto de vainilla y sigue batiendo hasta integrar.',
      'Une ambas mezclas hasta formar una masa.',
      'Cubre la masa y refrigera durante al menos 1 hora.',
      'Precalienta el horno a 180°C y forra una bandeja con papel para hornear.',
      'Divide la masa en pequeñas bolas y colócalas en la bandeja, dejando espacio entre cada una.',
      'Hornea 10-12 minutos o hasta que doren en los bordes.',
      'Deja enfriar unos minutos antes de pasarlas a una rejilla.',
      'Espolvorea con azúcar glas antes de servir, si gustas.',
    ],
  },
  {
    id: 'gelatina-matcha', te: 'matcha', tipo: 'platillo', nombre: 'Gelatina de Matcha',
    porciones: '2', imagen: 'assets/images/gelatina-matcha.jpeg',
    ingredientes: [
      '2 cucharaditas de NICE Imperial Matcha Green Tea Ceremonial',
      '1 taza de agua caliente',
      '3 cucharaditas de grenetina',
      '1/2 taza de azúcar',
      '1 taza de agua fría',
    ],
    instrucciones: [
      'Disuelve el matcha con agua caliente.',
      'En un tazón grande, revuelve la grenetina en polvo con la taza de agua fría.',
      'Agrega la mezcla de matcha caliente y el azúcar a la grenetina.',
      'Revuelve hasta que la grenetina y el azúcar se disuelvan por completo.',
      'Vierte en moldes individuales o un molde grande.',
      'Refrigera al menos 4 horas o hasta que cuaje firme.',
      'Desmolda y sirve.',
    ],
  },
  // ── ROOIBOS · BEBIDAS ──
  {
    id: 'rooibos-latte', te: 'rooibos', tipo: 'bebida', nombre: 'Rooibos Latte',
    porciones: '1', imagen: 'assets/images/rooibos-latte.jpeg',
    ingredientes: [
      '1 taza de leche caliente (cualquiera de tu preferencia)',
      '1 cucharadita de NICE Rooibos Red Tea',
      'Endulzante al gusto (azúcar, miel o jarabe)',
      'Extracto de vainilla al gusto',
    ],
    instrucciones: [
      'Mezcla la leche caliente con el rooibos y deja reposar 5-7 minutos.',
      'Endulza al gusto y, si lo deseas, agrega extracto de vainilla.',
      'Sirve caliente.',
    ],
  },
  {
    id: 'limonada-rooibos', te: 'rooibos', tipo: 'bebida', nombre: 'Limonada de Rooibos',
    porciones: '1', imagen: 'assets/images/limonada-rooibos.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Rooibos Red Tea',
      '1 taza de agua caliente',
      '1/4 de taza de jugo de limón',
      'Hielo al gusto',
      'Rodajas de limón al gusto',
      'Endulzante al gusto (azúcar, miel o jarabe)',
    ],
    instrucciones: [
      'En un vaso, agrega el rooibos y vierte el agua caliente, mezcla bien. Deja reposar 5-7 minutos y vuelve a mezclar.',
      'Agrega el jugo de limón y el endulzante. Mezcla hasta disolver.',
      'Sirve sobre hielo y decora con rodajas de limón.',
    ],
  },
  {
    id: 'rooibos-sangria', te: 'rooibos', tipo: 'bebida', nombre: 'Rooibos Rojo Sangría',
    porciones: '1', imagen: 'assets/images/rooibos-sangria.jpeg',
    ingredientes: [
      '4 cucharadas de NICE Rooibos Red Tea',
      '2 tazas de agua caliente',
      '4 tazas de jugo de uva',
      '1/2 taza de refresco de limón o toronja',
      '1/4 de taza de jugo de naranja',
      '1/4 de taza de jugo de limón',
      'Frutas frescas (naranjas, manzanas, fresas, uvas)',
      'Rodajas de naranja y limón para decorar',
      'Hielo al gusto',
    ],
    instrucciones: [
      'Mezcla el rooibos con el agua caliente.',
      'Deja reposar 10-15 minutos y mezcla bien.',
      'En una jarra grande, revuelve la mezcla de rooibos con el jugo de uva, el refresco, el jugo de naranja y el jugo de limón.',
      'Refrigera al menos 2 horas antes de servir.',
      'Sirve con frutas frescas, rodajas de limón, naranja y hielo al gusto.',
    ],
  },
  {
    id: 'rooibos-calientito-miel', te: 'rooibos', tipo: 'bebida', nombre: 'Rooibos Calientito con Miel',
    porciones: '1', imagen: 'assets/images/rooibos-calientito-miel.jpeg',
    ingredientes: [
      '1 taza de agua o leche caliente (cualquiera de tu preferencia)',
      '1 cucharadita de NICE Rooibos Red Tea',
      'Miel al gusto',
    ],
    instrucciones: [
      'Agrega el rooibos al agua o leche caliente y deja reposar 5-7 minutos.',
      'Endulza con miel al gusto y sirve caliente.',
    ],
  },
  // ── ROOIBOS · PLATILLOS ──
  {
    id: 'helado-rooibos', te: 'rooibos', tipo: 'platillo', nombre: 'Helado de Rooibos',
    porciones: '2', imagen: 'assets/images/helado-rooibos.jpeg',
    ingredientes: [
      '3 cucharaditas de NICE Rooibos Red Tea',
      '1 taza de leche caliente (cualquiera de tu preferencia)',
      '2 tazas de crema para batir',
      '3/4 de taza de azúcar',
    ],
    instrucciones: [
      'Disuelve el rooibos en leche caliente y deja reposar 10-15 minutos.',
      'En un tazón grande, revuelve la mezcla con la crema para batir y el azúcar hasta disolver.',
      'Refrigera al menos 4 horas o hasta que esté completamente fría.',
      'Vierte en un tazón y congela 45 minutos.',
      'Mezcla 2 minutos y repite el procedimiento hasta la consistencia deseada.',
      'Sirve y disfruta.',
    ],
  },
  {
    id: 'natilla-rooibos', te: 'rooibos', tipo: 'platillo', nombre: 'Natilla de Rooibos',
    porciones: '3', imagen: 'assets/images/natilla-rooibos.jpeg',
    ingredientes: [
      '2 tazas de leche caliente (cualquiera de tu preferencia)',
      '2 cucharaditas de NICE Rooibos Red Tea',
      '1/4 de taza de azúcar',
      '2 cucharadas de maicena',
      '2 yemas de huevo',
      '1 cucharadita de extracto de vainilla',
      'Fresas al gusto',
    ],
    instrucciones: [
      'Disuelve el rooibos en la leche caliente.',
      'En un sartén, mezcla el azúcar y la maicena.',
      'Agrega la leche de rooibos y las yemas de huevo. Cocina a fuego medio-bajo, revolviendo hasta que espese.',
      'Retira del fuego y agrega el extracto de vainilla.',
      'Deja enfriar y sirve con fresas al gusto.',
    ],
  },
  {
    id: 'panque-naranja-rooibos', te: 'rooibos', tipo: 'platillo', nombre: 'Panqué de Naranja & Rooibos',
    porciones: '7', imagen: 'assets/images/panque-naranja-rooibos.jpeg',
    ingredientes: [
      '1 1/2 tazas de harina',
      '2 cucharaditas de polvo de hornear',
      '1/2 cucharadita de sal',
      '1 taza de agua caliente',
      '2 cucharaditas de NICE Rooibos Red Tea',
      '1/2 taza de leche (cualquiera de tu preferencia)',
      '1/2 taza de jugo de naranja fresco',
      '1/2 taza de azúcar',
      '1/4 de taza de mantequilla derretida',
      '2 huevos',
      'Rodajas de naranja, pasas o arándanos al gusto',
    ],
    instrucciones: [
      'Precalienta el horno a 180°C y engrasa un molde para panqué.',
      'Mezcla la harina, el polvo para hornear y la sal.',
      'Disuelve el rooibos en el agua caliente y deja reposar 5-7 minutos.',
      'Separa dos mezclas: una con el rooibos, la leche, el jugo de naranja, el azúcar, la mantequilla y los huevos; otra con los secos.',
      'Une ambas mezclas hasta obtener una consistencia suave. Agrega pasas o arándanos si gustas.',
      'Vierte la masa en el molde y hornea 45-50 minutos (palillo debe salir limpio).',
      'Deja enfriar en el molde y luego desmolda.',
      'Decora con rodajas de naranja antes de servir.',
    ],
  },
  {
    id: 'pastel-miel-rooibos', te: 'rooibos', tipo: 'platillo', nombre: 'Pastel de Miel & Rooibos',
    porciones: '5', imagen: 'assets/images/pastel-miel-rooibos.jpeg',
    ingredientes: [
      '1 1/2 tazas de harina',
      '2 cucharaditas de polvo de hornear',
      '1/2 cucharadita de sal',
      '2 cucharaditas de NICE Rooibos Red Tea',
      '1 taza de agua caliente',
      '1/2 taza de leche',
      '1/2 taza de miel',
      '1/4 de taza de mantequilla derretida',
      '2 huevos',
      'Azúcar glas al gusto',
    ],
    instrucciones: [
      'Precalienta el horno a 180°C y engrasa un molde para pastel.',
      'Mezcla la harina, el polvo de hornear y la sal.',
      'Mezcla el rooibos con el agua caliente y deja reposar 5-7 minutos.',
      'Agrega el rooibos, la leche, la miel, la mantequilla y los huevos a los secos.',
      'Mezcla hasta que la masa esté suave.',
      'Vierte en el molde y hornea 30-35 minutos (palillo debe salir limpio).',
      'Deja enfriar en el molde y desmolda.',
      'Espolvorea con azúcar glas antes de servir.',
    ],
  },
  {
    id: 'paletas-rooibos-frutos-rojos', te: 'rooibos', tipo: 'platillo', nombre: 'Paletas de Rooibos con Frutos Rojos',
    porciones: '5 - 7 paletas', imagen: 'assets/images/paletas-rooibos-frutos-rojos.jpeg',
    ingredientes: [
      '1 cucharadita de NICE Rooibos Red Tea',
      '1 taza de agua caliente',
      '1 taza de frutos rojos (fresas, frambuesas, moras, etc.)',
      '1/4 de taza de yogurt natural',
      'Endulzante al gusto (azúcar, miel o jarabe)',
    ],
    instrucciones: [
      'Mezcla el rooibos con el agua caliente y el endulzante de tu preferencia.',
      'Deja enfriar la mezcla.',
      'Licúa el rooibos endulzado con los frutos rojos y el yogurt hasta obtener una mezcla suave.',
      'Vierte en moldes para paletas y congela al menos 4 horas.',
    ],
  },
  {
    id: 'sopa-tomate-fria', te: 'rooibos', tipo: 'platillo', nombre: 'Sopa de Tomate Fría',
    porciones: '4', imagen: 'assets/images/sopa-tomate-fria.jpeg',
    ingredientes: [
      '6 tomates maduros',
      '1 cucharada de NICE Rooibos Red Tea',
      '1/2 taza de agua caliente',
      '1 diente de ajo',
      '1/4 de taza de aceite de oliva',
      '2 cucharadas de vinagre balsámico',
      'Sal y pimienta al gusto',
      'Hojas de albahaca fresca para decorar',
    ],
    instrucciones: [
      'Mezcla el rooibos con el agua caliente.',
      'Licúa los tomates, el ajo, el aceite de oliva, el vinagre balsámico y la infusión de rooibos hasta obtener una mezcla suave.',
      'Sazona con sal y pimienta al gusto.',
      'Refrigera al menos 2 horas antes de servir.',
      'Sirve fría, decorada con hojas de albahaca fresca.',
    ],
  },
  // ── MATCHA · de "El Arte del Matcha: Origen, Beneficios y Recetas" ──
  {
    id: 'matcha-tradicional', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Tradicional',
    porciones: '1', imagen: 'assets/images/matcha-tradicional.png',
    ingredientes: [
      '2 cucharaditas de Té Matcha grado ceremonial',
      '70 ml de agua caliente (90°C)',
    ],
    instrucciones: [
      'En un bowl, pon las 2 cucharaditas de Té Matcha.',
      'Añade los 70 ml de agua caliente (90°C) y bate en seguida con un batidor de bambú (chasen).',
      'Para disolverlo, mueve primero lentamente para integrar, y después más enérgico hasta obtener espuma.',
      'Sirve en tu taza de preferencia.',
    ],
  },
  {
    id: 'tiramisu-matcha', te: 'matcha', tipo: 'platillo', nombre: 'Tiramisú con Matcha NICE',
    porciones: '4', imagen: 'assets/images/tiramisu-matcha.png',
    ingredientes: [
      '2 cditas de NICE Imperial Matcha Green Tea',
      '250 g de queso mascarpone',
      '200 ml de crema para batir bien fría',
      '3 cdas de azúcar (o monk fruit)',
      '1 cdita de esencia de vainilla',
      '1 taza de leche vegetal (almendra, avena o la que uses)',
      '1 paquete de soletas / ladyfingers / galletas suaves',
      'Matcha extra para espolvorear',
    ],
    instrucciones: [
      'Bate la crema hasta que forme picos suaves.',
      'En otro bowl, mezcla el mascarpone, el azúcar y la vainilla.',
      'Incorpora la crema batida con movimientos envolventes.',
      'Disuelve el matcha en la leche vegetal (debe estar tibia, no caliente).',
      'Remoja las galletas en la mezcla de matcha (rápido, sin empapar demasiado).',
      'En un molde, coloca capas de galletas y crema alternadas. Refrigera y espolvorea matcha extra antes de servir.',
    ],
  },
  {
    id: 'pancakes-matcha-avena', te: 'matcha', tipo: 'platillo', nombre: 'Pancakes de Matcha con Avena',
    porciones: '2 (6-8 pancakes pequeños)', imagen: 'assets/images/pancakes-matcha-avena.jpeg',
    ingredientes: [
      '1 taza de harina de avena o integral',
      '1 cucharadita de Matcha NICE Calidad Premium',
      '1 cucharadita de polvo para hornear',
      '1 pizca de sal',
      '1 huevo',
      '3/4 taza de leche vegetal o deslactosada',
      '1 cucharada de miel o monk fruit (opcional)',
      '1 cucharadita de extracto de vainilla',
      'Aceite de coco para engrasar',
      'Toppings sugeridos: yogur griego o de coco, fresas/plátano/moras, coco rallado, semillas de chía',
    ],
    instrucciones: [
      'Mezcla los ingredientes secos: harina, matcha, polvo para hornear y sal.',
      'Agrega los líquidos: huevo, leche, vainilla y miel. Mezcla hasta tener una masa suave.',
      'Engrasa ligeramente el sartén con aceite de coco y vierte pequeñas porciones de masa.',
      'Cocina a fuego medio-bajo, 2-3 minutos por lado, hasta que salgan burbujitas.',
      'Sirve, apila y decora con tus toppings favoritos.',
    ],
  },
  {
    id: 'galletas-matcha-choc-blanco', te: 'matcha', tipo: 'platillo', nombre: 'Galletas de Matcha y Chispas de Chocolate Blanco',
    porciones: '18 - 20 galletas', imagen: 'assets/images/galletas-matcha-choc-blanco.png',
    ingredientes: [
      '1 taza de harina para todo uso',
      '1 cucharadita de matcha en polvo',
      '1/2 cucharadita de bicarbonato de sodio',
      '1/4 cucharadita de sal',
      '1/2 taza (1 barra) de mantequilla sin sal, a temperatura ambiente',
      '1/2 taza de azúcar granulada',
      '1/4 taza de azúcar morena',
      '1 huevo grande',
      '1 cucharadita de extracto de vainilla',
      '1 taza de chispas de chocolate blanco',
    ],
    instrucciones: [
      'Precalienta el horno a 175°C (350°F). Cubre una bandeja con papel pergamino.',
      'Tamiza la harina, el matcha, el bicarbonato y la sal.',
      'Bate la mantequilla, el azúcar granulada y la morena hasta que estén suaves y esponjosos.',
      'Incorpora el huevo y el extracto de vainilla.',
      'Agrega gradualmente los secos a los húmedos, mezclando hasta combinar.',
      'Incorpora las chispas de chocolate blanco.',
      'Forma bolitas de masa en la bandeja, dejando espacio entre ellas.',
      'Hornea 10-12 minutos, o hasta que los bordes doren ligeramente.',
      'Deja enfriar unos minutos en la bandeja antes de pasarlas a una rejilla.',
    ],
  },
  {
    id: 'matcha-honey-hot-chocolate', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Honey Hot Chocolate',
    porciones: '1', imagen: 'assets/images/matcha-hot-chocolate.png',
    ingredientes: [
      '2 cucharaditas de Té Matcha',
      '20 ml de agua caliente',
      '1 taza de leche de coco',
      '2 cucharaditas de miel',
      '1/4 cucharadita de sal',
      '1 cucharadita de esencia de vainilla',
      '1 cucharadita de chocolate blanco',
      'Bombones para adornar',
    ],
    instrucciones: [
      'En una taza, mezcla el Té Matcha con 20 ml de agua caliente (90°C).',
      'En un recipiente, mezcla la leche de coco caliente (60°C) con el chocolate blanco hasta disolver.',
      'Agrega la miel, la esencia de vainilla y la pizca de sal.',
      'Vierte la preparación de matcha a la taza con la leche y chocolate, integra revolviendo suavemente.',
      'Decora con bombones al gusto.',
    ],
  },
  {
    id: 'iced-matcha', te: 'matcha', tipo: 'bebida', nombre: 'Iced Matcha',
    porciones: '1', imagen: 'assets/images/iced-matcha.png',
    ingredientes: [
      '2 cucharaditas de Té Matcha grado ceremonial',
      '70 ml de agua caliente',
      '3-4 cubitos de hielo',
    ],
    instrucciones: [
      'En un bowl, pon las 2 cucharaditas de Té Matcha.',
      'Añade los 70 ml de agua caliente (90°C) y bate con un batidor de bambú.',
      'Mueve primero lentamente para integrar, y después más enérgico hasta obtener espuma.',
      'Sirve en tu taza de preferencia y agrega los hielos.',
    ],
  },
  {
    id: 'matcha-soda', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Soda',
    porciones: '1', imagen: 'assets/images/matcha-soda.png',
    ingredientes: [
      '2 cucharaditas de Té Matcha grado ceremonial',
      '2 cucharaditas de Stevia',
      '100 ml de agua',
      '100 ml de agua gasificada',
      '2-3 cubitos de hielo',
      'Limón y hierbabuena al gusto',
    ],
    instrucciones: [
      'En un vaso, pon el Té Matcha, agrega el endulzante y disuelve con el agua.',
      'Añade el agua gasificada y el hielo.',
      'Añade un trozo de limón y hierbabuena.',
    ],
  },
  {
    id: 'matcha-latte-arroz', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Latte con Leche de Arroz (sin gluten)',
    porciones: '1', imagen: 'assets/images/matcha-latte-arroz.png',
    ingredientes: [
      '3 cucharaditas de Té Matcha grado Ceremonial',
      '90 ml de agua caliente',
      '30 ml de leche de arroz sin endulzar, caliente',
      'Edulcorante de tu preferencia',
    ],
    instrucciones: [
      'En un vaso, agrega el Té Matcha y vierte los 90 ml de agua caliente (90°C).',
      'Bate bien hasta conseguir bastante espuma (con chasen o mini batidora eléctrica).',
      'Prepara los 30 ml de leche de arroz caliente en un vaso aparte.',
      'Vierte la leche en el matcha lentamente.',
      'Añade el edulcorante de tu preferencia.',
    ],
  },
  {
    id: 'matcha-affogato', te: 'matcha', tipo: 'platillo', nombre: 'Matcha Affogato',
    porciones: '1', imagen: 'assets/images/matcha-affogato.png',
    ingredientes: [
      '100 g de helado de vainilla',
      '2 cucharaditas de Té Matcha grado Ceremonial',
      '20 ml de agua caliente',
      'Edulcorante al gusto',
    ],
    instrucciones: [
      'Pon las 2 cucharaditas de Té Matcha en un vaso.',
      'Agrega 20 ml de agua caliente (90°C) y bate bien hasta conseguir bastante espuma.',
      'Sirve una bola de helado de vainilla en un recipiente.',
      'Vierte la salsa de matcha encima del helado lentamente.',
    ],
  },
  {
    id: 'matcha-orange', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Orange',
    porciones: '1', imagen: 'assets/images/matcha-orange.png',
    ingredientes: [
      '1 cucharadita de Té Matcha grado Ceremonial',
      '10 g de azúcar (1 cucharada sopera)',
      '60 ml de agua caliente',
      '4-5 cubitos de hielo',
      '100 ml de zumo de naranja 100%',
    ],
    instrucciones: [
      'En un bowl, pon el matcha y el azúcar. Añade agua caliente (90°C) y bate bien.',
      'En un vaso alto, pon los cubitos de hielo y agrega el matcha ya batido.',
      'Espera 2 minutos a que se enfríe y añade lentamente el zumo de naranja.',
    ],
  },
  {
    id: 'matcha-mojito-smoothie', te: 'matcha', tipo: 'bebida', nombre: 'Matcha Mojito Smoothie',
    porciones: '2', imagen: 'assets/images/matcha-mojito-smoothie.png',
    ingredientes: [
      '1 taza de agua de coco',
      '1 cucharadita de Té Matcha grado Ceremonial',
      '1 taza de agua',
      'Jugo de 2 limones',
      '1 aguacate maduro pequeño',
      '1 hoja grande de menta',
      '1 1/2 taza de hojas de espinaca',
      '1 cucharadita de vainilla en polvo',
      '1/2 taza de cubitos de hielo',
    ],
    instrucciones: [
      'Mezcla todos los ingredientes en la licuadora y disfruta.',
    ],
  },
  {
    id: 'matcha-chia-pudding', te: 'matcha', tipo: 'platillo', nombre: 'Matcha Chia Pudding',
    porciones: '2', imagen: 'assets/images/matcha-chia-pudding.png',
    ingredientes: [
      '1 taza de leche de almendras',
      '1/2 cucharadita de Té Matcha',
      '1/3 taza de semillas de chía',
      'Endulzante a elección',
      '1 cucharadita de extracto de vainilla',
    ],
    instrucciones: [
      'Mezcla en la licuadora la leche de almendras, el endulzante, la vainilla y el matcha.',
      'En un tazón, agrega las semillas de chía junto con la mezcla anterior.',
      'Refrigera por lo menos 15 minutos.',
      'Acompaña con tus toppings preferidos.',
    ],
  },
  {
    id: 'natilla-matcha', te: 'matcha', tipo: 'platillo', nombre: 'Natilla de Matcha',
    porciones: '4', imagen: 'assets/images/natilla-matcha.jpeg',
    ingredientes: [
      '2 tazas de leche',
      '2 cucharadas de maicena',
      '1/3 de taza de azúcar',
      '1 cucharadita de NICE Imperial Matcha Green Tea',
      '1 cucharada de extracto de vainilla',
    ],
    instrucciones: [
      'En un bowl mezcla la maicena, el azúcar y el matcha.',
      'En una olla, calienta a fuego lento la leche y el extracto de vainilla.',
      'Añade a la olla el resto de los ingredientes y comienza a remover hasta que hierva.',
      'Cuando llegue al punto de ebullición, retírala del fuego y viértela en pequeños cuencos.',
      'Cuando estén a temperatura ambiente, refrigéralos unas horas.',
    ],
  },
]

const PRODUCTOS = [
  {
    id: 'matcha-ceremonial', nombre: 'Matcha Ceremonial en Sobres', te: 'matcha',
    imagen: 'assets/images/matcha-section.jpeg',
    sku: 'T31109',
    descripcion: 'Descubre la pureza y la tradición del país del sol naciente en cada sorbo, con nuestro té verde pulverizado. Disfruta de este Matcha Ceremonial 100% puro en su presentación de 28 sobres individuales. Perfecto para quienes buscan llenarse de energía con todos los beneficios del té auténtico de Japón. Lleva tu matcha a donde quiera que vayas.',
    caracteristicas: ['Hoja de té verde molida', 'Bolsa con 28 sobres de 2 gramos c/u'],
    presentacion: '28 sobres de 2 g c/u',
    precio: 224.50,
    puntos: 18,
  },
  {
    id: 'matcha-premium-lime', nombre: 'Matcha Premium Quality — Sabor Lime', te: 'matcha',
    imagen: 'assets/images/limonada-matcha.jpeg',
    descripcion: 'Té verde matcha premium con un toque de limón, en sobres individuales listos para llevar.',
    presentacion: '28 sobres',
    precio: null,
  },
  {
    id: 'rooibos-red-tea', nombre: 'NICE Rooibos Red Tea', te: 'rooibos',
    imagen: 'assets/images/rooibos-section.jpeg',
    descripcion: 'Té rojo en polvo, sin cafeína, sabor suave. Ideal para toda la familia, caliente o frío.',
    presentacion: '3.52 oz (100 g)',
    precio: null,
  },
]

const ORIGEN_MATCHA = {
  titulo: 'Origen del Matcha',
  texto: [
    'El matcha, un polvo fino de hojas de té verde especialmente cultivadas y procesadas, tiene una rica historia que se remonta a la antigua China. Fue en Japón donde su preparación y consumo se elevaron a una forma de arte y espiritualidad, convirtiéndose en el centro de la ceremonia del té japonesa.',
    'Se dice que el matcha fue introducido en Japón en el siglo XII por el monje budista Eisai, quien regresó de China con semillas de té y el conocimiento para prepararlo en polvo. Reconoció sus beneficios para la salud, particularmente su capacidad para promover la meditación y la concentración en los monjes.',
    'Las hojas utilizadas, conocidas como tencha, se cultivan a la sombra durante las últimas semanas antes de la cosecha — esto aumenta su clorofila y aminoácidos, dando el color verde vibrante y el sabor umami distintivo del matcha. Después se cuecen al vapor para detener la oxidación, se secan y se muelen lentamente en molinos de piedra hasta obtener un polvo fino.',
  ],
}

const PREPARACION_MATCHA = {
  titulo: 'Modo de preparación',
  items: [
    { t: 'Bebida caliente', d: 'En una taza de agua tibia, vacía el contenido de un sobre o cuchara medidora y revuelve hasta deshacer los grumos. Disfruta.' },
    { t: 'Bebida fría', d: 'Vacía el contenido de un sobre o cuchara medidora en una botella de 600 ml, o en un vaso con hielo o agua mineral. Revuelve y disfruta.' },
    { t: 'Tip', d: 'También se puede preparar con limonada, naranjada, agua de piña, y más.' },
  ],
}

const INFO_TES = {
  matcha: {
    titulo: 'Matcha',
    beneficios: [
      { t: 'Té verde concentrado', d: 'Una taza de matcha puede tener el valor nutricional de 10 tazas de té verde.' },
      { t: 'Rico en antioxidantes', d: 'Está repleto de catequinas, que ayudan a combatir los radicales libres y reducen el daño celular — más que cualquier otra variedad de té.' },
      { t: 'Energía sostenida y enfoque mental', d: 'La combinación de L-teanina y cafeína da una energía sostenida y claridad mental, sin los nervios asociados al café — la teína se procesa más lento, por lo que la energía dura más.' },
      { t: 'Acelera el metabolismo', d: 'Puede aumentar la termogénesis (la velocidad a la que el cuerpo quema calorías) y promover la oxidación de grasas.' },
      { t: 'Desintoxicación natural', d: 'Su alta concentración de clorofila lo convierte en un potente agente desintoxicante, ayudando a eliminar toxinas del cuerpo.' },
      { t: 'Ayuda a mejorar la apariencia de la piel', d: 'Contiene nutrientes sorprendentes para tu piel, como la clorofila y vitaminas.' },
      { t: 'Fortalece el sistema inmunológico', d: 'Contiene vitaminas A y C, potasio, hierro y calcio — nutrientes esenciales para un sistema inmune saludable.' },
      { t: 'Salud del corazón', d: 'El consumo regular de té verde, incluido el matcha, puede contribuir a la salud cardiovascular al reducir el colesterol LDL y los triglicéridos.' },
    ],
  },
  rooibos: {
    titulo: 'Rooibos',
    beneficios: [
      { t: 'Sin cafeína', d: 'El té rooibos es libre de cafeína, excelente opción para quienes tienen problemas para dormir.' },
      { t: 'Relajante', d: 'Tiene propiedades calmantes, puede ayudar a reducir el estrés y promover un descanso profundo.' },
      { t: 'Buena opción para niños', d: 'Por su sabor suave, el rooibos suele gustarle a los niños — una alternativa más saludable a las bebidas azucaradas.' },
    ],
  },
}
